from enum import StrEnum


class EventType(StrEnum):
    """
    Standard event types for the SENTINEL AI Event Bus.
    """

    CALL_STARTED = "CALL_STARTED"
    CALL_ENDED = "CALL_ENDED"
    AUDIO_FRAME_RECEIVED = "AUDIO_FRAME_RECEIVED"
    TRANSCRIPT_PARTIAL = "TRANSCRIPT_PARTIAL"
    TRANSCRIPT_FINAL = "TRANSCRIPT_FINAL"
    THREAT_DETECTED = "THREAT_DETECTED"
    A2A_MESSAGE = "A2A_MESSAGE"
    EVIDENCE_SEALED = "EVIDENCE_SEALED"
    KILL_SWITCH_TRIGGERED = "KILL_SWITCH_TRIGGERED"
    INCIDENT_CREATED = "INCIDENT_CREATED"
    ERROR_OCCURRED = "ERROR_OCCURRED"
